# Generated by Django 6.0.3 on 2026-09-21 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_alter_exercisemuscle_unique_together_and_more'),
        ('muscles', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='musclegroupmuscle',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='musclegroup',
            name='muscles',
        ),
        migrations.RemoveField(
            model_name='musclegroupmuscle',
            name='muscle',
        ),
        migrations.RemoveField(
            model_name='musclegroupmuscle',
            name='muscle_group',
        ),
        migrations.DeleteModel(
            name='MuscleHead',
        ),
        migrations.DeleteModel(
            name='Muscle',
        ),
        migrations.DeleteModel(
            name='MuscleGroupMuscle',
        ),
    ]
