# Generated by Django 6.0.3 on 2026-09-21 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_remove_workoutexercise_execution_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='notes',
        ),
    ]
