# Generated by Django 6.0.3 on 2026-09-21 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_alter_exercise_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exercisemuscle',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='exercisemuscle',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exercisemuscle',
            name='muscle',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='target_muscle',
        ),
        migrations.DeleteModel(
            name='ExerciseInstruction',
        ),
        migrations.DeleteModel(
            name='ExerciseMuscle',
        ),
    ]
